Sys.setlocale("LC_TIME", "en_US.UTF-8")
power.df <- read.csv("household_power_consumption.txt", header = T, sep = ";", colClasses = "character")
power.df$Date <- as.Date(power.df$Date, format = "%d/%m/%Y")
power2.df <- subset(power.df, (Date >= "2007-02-01") & (Date <= "2007-02-02"))
power2.df$Date.Time <- paste(power2.df$Date, power2.df$Time)
power2.df$Date.Time <- strptime(power2.df$Date.Time, "%Y-%m-%d %H:%M:%S")
sapply(power2.df[, 7:9], as.numeric)
png(filename="plot3.png",  width = 480, height = 480, units = "px")
plot(x = power2.df$Date.Time, y = power2.df$Sub_metering_1, ylim = range(1:40), type = "l", ylab = "Energy sub metering", xlab ="")
par(new = TRUE)
plot(x = power2.df$Date.Time, y = power2.df$Sub_metering_2, ylim = range(1:40), col = "red", type = "l", ylab = "Energy sub metering", xlab ="")
par(new = TRUE)
plot(x = power2.df$Date.Time, y = power2.df$Sub_metering_3, ylim = range(1:40), col = "blue", type = "l", ylab = "Energy sub metering", xlab ="")
legend("topright", names(power2.df[, 7:9]), lty = 1, col = c("black", "red", "blue"))
dev.off()